import type { Metadata } from '../storageTypes';

export const rigMetadataFixture: Metadata = {
    rigMetadataVersion: 1,
    client: { id: 'rig', name: 'Rig', version: '0.0.30' },
    provider: { id: 'codex', kind: 'codex', name: 'OpenAI Codex' },
    providers: [
        { id: 'codex', kind: 'codex', name: 'OpenAI Codex' },
        { id: 'claude', kind: 'claude', name: 'Anthropic Claude' },
    ],
    model: { providerId: 'codex', id: 'shared-model' },
    models: [
        {
            providerId: 'codex',
            providerKind: 'codex',
            providerName: 'OpenAI Codex',
            provider: { id: 'codex', kind: 'codex', name: 'OpenAI Codex' },
            id: 'shared-model',
            code: 'shared-model',
            name: 'GPT Shared',
            value: 'GPT Shared',
            contextWindow: 200_000,
            serviceTiers: ['fast'],
            thinkingLevels: ['low', 'medium', 'high'],
            defaultThinkingLevel: 'high',
        },
        {
            providerId: 'claude',
            providerKind: 'claude',
            providerName: 'Anthropic Claude',
            provider: { id: 'claude', kind: 'claude', name: 'Anthropic Claude' },
            id: 'shared-model',
            code: 'shared-model',
            name: 'Claude Shared',
            value: 'Claude Shared',
            contextWindow: 180_000,
            serviceTiers: [],
            thinkingLevels: ['low', 'high', 'max'],
            defaultThinkingLevel: 'max',
        },
    ],
    currentModelProviderId: 'codex',
    currentModelCode: 'shared-model',
    permissionMode: 'auto',
    currentOperatingModeCode: 'auto',
    operatingModes: [
        { code: 'auto', value: 'Auto', description: 'Uses the workspace sandbox and asks before actions that need full access.', kind: 'safe-yolo' },
        { code: 'workspace_write', value: 'Workspace write', description: 'Allows workspace changes while blocking shell network and outside writes.', kind: 'default' },
        { code: 'read_only', value: 'Read only', description: 'Allows inspection without workspace changes or shell network access.', kind: 'read-only' },
        { code: 'full_access', value: 'Full access', description: 'Removes Rig filesystem, shell, and network restrictions.', kind: 'yolo' },
    ],
    reasoning: { current: 'high', levels: ['low', 'medium', 'high'] },
    currentThoughtLevelCode: 'high',
    thoughtLevels: [
        { code: 'low', value: 'low' },
        { code: 'medium', value: 'medium' },
        { code: 'high', value: 'high' },
    ],
    session: { status: 'running', permissionMode: 'auto', modelLocked: false, serviceTier: 'fast' },
    capabilities: {
        abort: true,
        attachments: { enabled: true, maxBytes: 10 * 1024 * 1024, mediaTypes: ['image/*'] },
        files: { browse: true, read: true, search: true, write: true },
        modelSelection: true,
        reasoningSelection: true,
        permissionModeSelection: true,
        resume: false,
        rpcMethods: ['abort', 'bash', 'readFile', 'writeFile', 'ripgrep'],
        shell: true,
        steering: true,
    },
    activity: {
        subagents: { running: 1, queued: 2, total: 4 },
        workflows: { running: 1, total: 2 },
        processes: { running: 2 },
        tasks: { pending: 3, inProgress: 1, completed: 5, total: 9 },
    },
    mcpServers: [{ name: 'github', status: 'connected' }],
    tools: ['bash', 'read_file'],
    skills: ['review'],
    name: 'Rig session',
    summary: { text: 'Rig integration', updatedAt: 1 },
    path: '/tmp/rig-project',
    host: 'rig-host',
    os: 'darwin',
    flavor: 'codex',
    startedBy: 'daemon',
    startedFromDaemon: true,
};
